# ::::: GLOBAL ::::::
SEED 3725261


# ::::: SERVER ::::::

# artificial delay for I/O related tasks i.e. lookup and store
LOOKUP_DELAY 0
STORE_DELAY 0

# duration (in millisecond) from current time to be used in prediction i.e., what would be the status in <Duration> from now
# value of 1000 means it is 1s from now 
ESTIMATE_PERIOD 10000

# number of latest entries to keep in various lists (arrival, request, etc.) that being considered for calculation/prediction
ENTRY_SIZE 10

# number of random nodes to select during data placement decision, only applicable for PT (power of two choices)
PT_NODE_COUNT 2

# ::::: CLIENT & MONITOR ::::::

# timeout unit is in milliseconds
CLIENT_NUM_THREAD 1
CLIENT_CONNECT_TIMEOUT 5000
CLIENT_READ_TIMEOUT 30000
CLIENT_WRITE_TIMEOUT 30000

# artificial delay for clients, in milliseconds
CLIENT_STORE_DELAY 0
CLIENT_LOOKUP_DELAY 0

# warmup period, in seconds
# used by the Client app
WARMUP_PERIOD 600

# status collection period, in milliseconds, value of 10000 means every 10 seconds
# used by the Monitor app
STATUS_PERIOD 10000
