# ::::: NODE ::::::
MAX_ATTEMPT 100

# message sender
CONNECT_TIMEOUT 5000
READ_TIMEOUT 10000
WRITE_TIMEOUT 10000

# virtual nodes host by this node
VIRTUAL_NODES 1

DATA_PATH data
DATA_INPUT_PATH data/input 
DATA_TEMP_PATH data/tmp
# maximum block size, in kilobytes (KB)
DATA_SIZE 10240

IDENTIFIER_SIZE 128
BUCKET_SIZE 20
FIND_NODE_SIZE 20
MAXIMUM_LAST_SEEN_AGE_TO_CONSIDER_ALIVE = 300
PING_SCHEDULE_TIME_VALUE 20
# 4 = java.util.concurrent.TimeUnit.SECONDS
PING_SCHEDULE_TIME_UNIT = 4
# number of threads = number of CPU cores * 2 (typical)
DHT_EXECUTOR_POOL_SIZE 2
SCHEDULED_EXECUTOR_POOL_SIZE = 1
# 0 = False, 1 = True
ENABLED_FIRST_STORE_REQUEST_FORCE_PASS = false





